### ISSUE TITLE
Fix : 이미지 박스 이미지 업로드 실패시 핸들링 필요

### ISSUE THREAD

**Issue by SonSangjoon** [moramoram/client#203]
![스크린샷 2022-02-04 오후 6 16 14](https://user-images.githubusercontent.com/74908906/152503296-e3d4c301-be2c-4667-9f1c-5e467ea1a1cf.png)

이미지 태그에 onError를 붙이거나 다른 방법으로 수정할 필요가 있을 것 같습니다.

**Comment by devpla** [comment]
확인했습니당
