### ISSUE TITLE
Fix : 메인 페이지 이미지 사이즈 에러 수정

### ISSUE THREAD

**Issue by SonSangjoon** [moramoram/client#231]
- 화면 축소시 로고 사이즈
object-fit: cover를 사용해서 수정하거나 다른 방식 필요
![스크린샷 2022-02-07 오후 10 59 24](https://user-images.githubusercontent.com/74908906/152802059-331ae052-d147-453f-b7c1-976cd63f96f8.png)

**Comment by devpla** [comment]
#215 이슈에서 해결할 예정이에요 :)
