### ISSUE TITLE
Fix : 그리드 로딩 UI 오류 수정

### ISSUE THREAD

**Issue by SonSangjoon** [moramoram/client#376]
![스크린샷 2022-03-09 오전 2 40 17](https://user-images.githubusercontent.com/74908906/157294713-16b51fc3-0c52-41f9-a82d-ffc35b09677e.png)

제목, 소제목 로딩 UI가 표시가 되지 않음

**Comment by devpla** [comment]
뭐지 😥

**Comment by SonSangjoon** [comment]
![스크린샷 2022-03-09 오전 8 01 42](https://user-images.githubusercontent.com/74908906/157340503-37f415a1-f2d9-4e45-b3ac-273ff207e777.png)

그리드 레이아웃도 수정이 필요합니다.
